package render

import (
	"strings"
	"testing"

	"github.com/sparkfabrik/github-ci-assembler/internal/config"
)

// helper: check if a job ID appears as a YAML mapping key (not inside a comment).
// A YAML key line looks like "  job-id:" with leading spaces but no "#".
func hasJobEntry(output, jobID string) bool {
	needle := jobID + ":"
	for _, line := range strings.Split(output, "\n") {
		trimmed := strings.TrimSpace(line)
		if strings.HasPrefix(trimmed, "#") {
			continue // skip comment lines
		}
		if strings.HasPrefix(trimmed, needle) {
			return true
		}
	}
	return false
}

// helper: render an AssemblyResult and return the output as a string.
func mustRender(t *testing.T, result *config.AssemblyResult) string {
	t.Helper()
	out, err := Render(result)
	if err != nil {
		t.Fatalf("Render() error: %v", err)
	}
	return string(out)
}

// helper: build a minimal AssemblyResult with the given jobs and optional workflow props.
func minimalResult(jobs []*config.AssembledJob) *config.AssemblyResult {
	return &config.AssemblyResult{
		Workflow: config.WorkflowProperties{
			Name: "CI",
		},
		Jobs:        jobs,
		SourceFiles: []string{"configuration.yml"},
	}
}

// ---------------------------------------------------------------------------
// TestRender_Header
// ---------------------------------------------------------------------------

func TestRender_Header(t *testing.T) {
	tests := []struct {
		name        string
		sourceFiles []string
		wantSubstr  []string
	}{
		{
			name:        "header includes multiple source files",
			sourceFiles: []string{"conf.yml", "pkg_a.yml"},
			wantSubstr: []string{
				"AUTO-GENERATED by gh-ci-assembler",
				"Source: conf.yml, pkg_a.yml",
			},
		},
		{
			name:        "header includes single source file",
			sourceFiles: []string{"conf.yml"},
			wantSubstr: []string{
				"AUTO-GENERATED",
				"Source: conf.yml",
			},
		},
	}

	for _, tc := range tests {
		t.Run(tc.name, func(t *testing.T) {
			result := &config.AssemblyResult{
				Workflow:    config.WorkflowProperties{Name: "CI"},
				Jobs:        []*config.AssembledJob{},
				SourceFiles: tc.sourceFiles,
			}
			out := mustRender(t, result)
			for _, s := range tc.wantSubstr {
				if !strings.Contains(out, s) {
					t.Errorf("output missing %q\n\nGot:\n%s", s, out)
				}
			}
		})
	}
}

// ---------------------------------------------------------------------------
// TestRender_WorkflowPropertyOrder
// ---------------------------------------------------------------------------

func TestRender_WorkflowPropertyOrder(t *testing.T) {
	result := &config.AssemblyResult{
		Workflow: config.WorkflowProperties{
			Name:        "CI",
			On:          map[string]any{"push": map[string]any{}},
			Defaults:    map[string]any{"run": map[string]any{"shell": "bash"}},
			Env:         map[string]any{"GO_ENV": "test"},
			Permissions: map[string]any{"contents": "read"},
		},
		Jobs:        []*config.AssembledJob{},
		SourceFiles: []string{"conf.yml"},
	}

	out := mustRender(t, result)

	keys := []string{"name:", "on:", "defaults:", "env:", "permissions:", "jobs:"}
	prevIdx := -1
	for _, key := range keys {
		idx := strings.Index(out, "\n"+key)
		if idx == -1 {
			// Try without newline prefix for first occurrence.
			idx = strings.Index(out, key)
		}
		if idx == -1 {
			t.Fatalf("key %q not found in output:\n%s", key, out)
		}
		if idx <= prevIdx {
			t.Errorf("key %q (at %d) appears before or at same position as previous key (at %d)", key, idx, prevIdx)
		}
		prevIdx = idx
	}
}

// ---------------------------------------------------------------------------
// TestRender_WorkflowPropertyOmission
// ---------------------------------------------------------------------------

func TestRender_WorkflowPropertyOmission(t *testing.T) {
	t.Run("nil properties omitted", func(t *testing.T) {
		result := &config.AssemblyResult{
			Workflow: config.WorkflowProperties{
				Name: "CI",
				// On, Defaults, Env, Permissions are all nil.
			},
			Jobs:        []*config.AssembledJob{},
			SourceFiles: []string{"conf.yml"},
		}

		out := mustRender(t, result)

		if !strings.Contains(out, "name: CI") {
			t.Errorf("expected 'name: CI' in output:\n%s", out)
		}
		if !strings.Contains(out, "jobs:") {
			t.Errorf("expected 'jobs:' in output:\n%s", out)
		}

		for _, absent := range []string{"\non:", "\ndefaults:", "\nenv:", "\npermissions:"} {
			if strings.Contains(out, absent) {
				t.Errorf("expected %q to be absent from output:\n%s", absent, out)
			}
		}
	})

	t.Run("empty name omitted", func(t *testing.T) {
		result := &config.AssemblyResult{
			Workflow: config.WorkflowProperties{
				Name: "", // Empty name should be omitted.
			},
			Jobs:        []*config.AssembledJob{},
			SourceFiles: []string{"conf.yml"},
		}

		out := mustRender(t, result)

		if strings.Contains(out, "\nname:") {
			t.Errorf("expected 'name:' to be absent when Name is empty:\n%s", out)
		}
		if !strings.Contains(out, "jobs:") {
			t.Errorf("expected 'jobs:' in output:\n%s", out)
		}
	})
}

// ---------------------------------------------------------------------------
// TestRender_StageComments
// ---------------------------------------------------------------------------

func TestRender_StageComments(t *testing.T) {
	tests := []struct {
		name       string
		jobs       []*config.AssembledJob
		wantSubstr []string
		wantOrder  []string // substrings that must appear in this order
	}{
		{
			name: "single stage comment",
			jobs: []*config.AssembledJob{
				{ID: "build--base--job1", Stage: "build", DisplayName: "job1 - base [build]", Properties: map[string]any{"runs-on": "ubuntu-latest"}},
				{ID: "build--base--job2", Stage: "build", DisplayName: "job2 - base [build]", Properties: map[string]any{"runs-on": "ubuntu-latest"}},
			},
			wantSubstr: []string{"Stage: build"},
		},
		{
			name: "multiple jobs in same stage all rendered",
			jobs: []*config.AssembledJob{
				{ID: "build--base--job1", Stage: "build", DisplayName: "job1 - base [build]", Properties: map[string]any{"runs-on": "ubuntu-latest"}},
				{ID: "build--base--job2", Stage: "build", DisplayName: "job2 - base [build]", Properties: map[string]any{"runs-on": "ubuntu-latest"}},
			},
			wantSubstr: []string{"build--base--job1:", "build--base--job2:"},
		},
		{
			name: "multiple stage comments in order",
			jobs: []*config.AssembledJob{
				{ID: "build--base--job1", Stage: "build", DisplayName: "job1 - base [build]", Properties: map[string]any{"runs-on": "ubuntu-latest"}},
				{ID: "test--base--job2", Stage: "test", DisplayName: "job2 - base [test]", Properties: map[string]any{"runs-on": "ubuntu-latest"}},
			},
			wantSubstr: []string{"Stage: build", "Stage: test"},
			wantOrder:  []string{"Stage: build", "Stage: test"},
		},
	}

	for _, tc := range tests {
		t.Run(tc.name, func(t *testing.T) {
			out := mustRender(t, minimalResult(tc.jobs))
			for _, s := range tc.wantSubstr {
				if !strings.Contains(out, s) {
					t.Errorf("output missing %q\n\nGot:\n%s", s, out)
				}
			}
			if len(tc.wantOrder) > 1 {
				prevIdx := -1
				for _, s := range tc.wantOrder {
					idx := strings.Index(out, s)
					if idx <= prevIdx {
						t.Errorf("%q (at %d) should appear after previous (at %d)", s, idx, prevIdx)
					}
					prevIdx = idx
				}
			}
		})
	}
}

// ---------------------------------------------------------------------------
// TestRender_DisabledJobComments
// ---------------------------------------------------------------------------

func TestRender_DisabledJobComments(t *testing.T) {
	t.Run("stage with active and disabled jobs", func(t *testing.T) {
		jobs := []*config.AssembledJob{
			{ID: "build--base--active", Stage: "build", DisplayName: "active - base [build]", Properties: map[string]any{"runs-on": "ubuntu-latest"}},
			{ID: "build--base--removed", Stage: "build", DisplayName: "removed - base [build]", Properties: map[string]any{}, Disabled: true, DisabledComment: "DISABLED by project.yml"},
		}
		out := mustRender(t, minimalResult(jobs))

		// The active job must be rendered as a YAML key.
		if !hasJobEntry(out, "build--base--active") {
			t.Errorf("expected active job entry in output:\n%s", out)
		}
		// The disabled job must NOT appear as a YAML key (only in a comment).
		if hasJobEntry(out, "build--base--removed") {
			t.Errorf("disabled job should not be rendered as a job entry:\n%s", out)
		}
		// The disabled comment must appear.
		if !strings.Contains(out, "build--base--removed: DISABLED by project.yml") {
			t.Errorf("expected disabled comment in output:\n%s", out)
		}
	})

	t.Run("stage with only disabled jobs after active stage", func(t *testing.T) {
		jobs := []*config.AssembledJob{
			{ID: "build--base--job1", Stage: "build", DisplayName: "job1 - base [build]", Properties: map[string]any{"runs-on": "ubuntu-latest"}},
			{ID: "test--base--removed", Stage: "test", DisplayName: "removed - base [test]", Properties: map[string]any{}, Disabled: true, DisabledComment: "DISABLED by project.yml"},
		}
		out := mustRender(t, minimalResult(jobs))

		// The active job in build must be rendered.
		if !hasJobEntry(out, "build--base--job1") {
			t.Errorf("expected active job entry in output:\n%s", out)
		}
		// The disabled-only stage must produce a comment but no job entry.
		if hasJobEntry(out, "test--base--removed") {
			t.Errorf("disabled job should not be rendered as a job entry:\n%s", out)
		}
		// The stage comment and disabled comment should still appear.
		if !strings.Contains(out, "Stage: test") {
			t.Errorf("expected stage comment for disabled-only stage:\n%s", out)
		}
		if !strings.Contains(out, "test--base--removed: DISABLED by project.yml") {
			t.Errorf("expected disabled comment in output:\n%s", out)
		}
	})

	t.Run("disabled-only stage as first stage silently dropped", func(t *testing.T) {
		// When the only stage has disabled jobs and no active jobs,
		// there is no prior YAML node to attach the foot comment to,
		// so the disabled comment is silently dropped.
		jobs := []*config.AssembledJob{
			{ID: "build--base--removed", Stage: "build", DisplayName: "removed - base [build]", Properties: map[string]any{}, Disabled: true, DisabledComment: "DISABLED by project.yml"},
		}
		out := mustRender(t, minimalResult(jobs))

		// No job entry should be rendered.
		if hasJobEntry(out, "build--base--removed") {
			t.Errorf("disabled job should not be rendered as a job entry:\n%s", out)
		}
		// The foot comment has nowhere to attach — verify no stage comment appears.
		if strings.Contains(out, "Stage: build") {
			t.Errorf("expected disabled-only first stage comment to be dropped (no prior node to attach to):\n%s", out)
		}
	})

	t.Run("empty stage skipped entirely", func(t *testing.T) {
		// A stage with no jobs at all (neither active nor disabled) should not appear.
		// We simulate this by only having jobs in "build" — no "test" stage jobs exist.
		jobs := []*config.AssembledJob{
			{ID: "build--base--job1", Stage: "build", DisplayName: "job1 - base [build]", Properties: map[string]any{"runs-on": "ubuntu-latest"}},
		}
		out := mustRender(t, minimalResult(jobs))

		if strings.Contains(out, "Stage: test") {
			t.Errorf("stage with no jobs should not appear:\n%s", out)
		}
	})
}

// ---------------------------------------------------------------------------
// TestRender_JobKeyOrder
// ---------------------------------------------------------------------------

func TestRender_JobKeyOrder(t *testing.T) {
	jobs := []*config.AssembledJob{
		{
			ID:          "build--base--job1",
			Stage:       "build",
			DisplayName: "job1 - base [build]",
			Properties: map[string]any{
				"runs-on": "ubuntu-latest",
				"env":     map[string]any{"GO_ENV": "test"},
				"steps": []any{
					map[string]any{"name": "Checkout", "uses": "actions/checkout@v4"},
				},
				"custom-x": "value-x",
				"custom-a": "value-a",
			},
		},
	}

	out := mustRender(t, minimalResult(jobs))

	// Extract the job block (everything after "build--base--job1:").
	jobStart := strings.Index(out, "build--base--job1:")
	if jobStart == -1 {
		t.Fatalf("job not found in output:\n%s", out)
	}
	jobBlock := out[jobStart:]

	// Canonical order: name, runs-on, env, steps, then unknown keys alphabetically.
	orderedKeys := []string{"name:", "runs-on:", "env:", "steps:", "custom-a:", "custom-x:"}
	prevIdx := -1
	for _, key := range orderedKeys {
		idx := strings.Index(jobBlock, key)
		if idx == -1 {
			t.Fatalf("key %q not found in job block:\n%s", key, jobBlock)
		}
		if idx <= prevIdx {
			t.Errorf("key %q (at %d) should appear after previous key (at %d)\n\nJob block:\n%s", key, idx, prevIdx, jobBlock)
		}
		prevIdx = idx
	}
}

// ---------------------------------------------------------------------------
// TestRender_NeedsOmittedWhenEmpty
// ---------------------------------------------------------------------------

func TestRender_NeedsOmittedWhenEmpty(t *testing.T) {
	jobs := []*config.AssembledJob{
		{
			ID:            "build--base--job1",
			Stage:         "build",
			DisplayName:   "job1 - base [build]",
			ComputedNeeds: nil, // No needs.
			Properties:    map[string]any{"runs-on": "ubuntu-latest"},
		},
	}

	out := mustRender(t, minimalResult(jobs))

	// Extract the job block.
	jobStart := strings.Index(out, "build--base--job1:")
	if jobStart == -1 {
		t.Fatalf("job not found in output:\n%s", out)
	}
	jobBlock := out[jobStart:]

	if strings.Contains(jobBlock, "needs:") {
		t.Errorf("expected 'needs:' to be absent when ComputedNeeds is nil:\n%s", jobBlock)
	}
}

// ---------------------------------------------------------------------------
// TestRender_NeedsFlowStyle
// ---------------------------------------------------------------------------

func TestRender_NeedsFlowStyle(t *testing.T) {
	t.Run("multiple needs entries", func(t *testing.T) {
		jobs := []*config.AssembledJob{
			{
				ID:            "test--base--job1",
				Stage:         "test",
				DisplayName:   "job1 - base [test]",
				ComputedNeeds: []string{"build--base--a", "build--base--b"},
				Properties:    map[string]any{"runs-on": "ubuntu-latest"},
			},
		}

		out := mustRender(t, minimalResult(jobs))

		if !strings.Contains(out, "needs: [build--base--a, build--base--b]") {
			t.Errorf("expected flow-style needs array in output:\n%s", out)
		}
	})

	t.Run("single needs entry", func(t *testing.T) {
		jobs := []*config.AssembledJob{
			{
				ID:            "test--base--job1",
				Stage:         "test",
				DisplayName:   "job1 - base [test]",
				ComputedNeeds: []string{"build--base--a"},
				Properties:    map[string]any{"runs-on": "ubuntu-latest"},
			},
		}

		out := mustRender(t, minimalResult(jobs))

		if !strings.Contains(out, "needs: [build--base--a]") {
			t.Errorf("expected flow-style single-element needs array in output:\n%s", out)
		}
	})
}

// ---------------------------------------------------------------------------
// TestRender_EmptyJobsList
// ---------------------------------------------------------------------------

func TestRender_EmptyJobsList(t *testing.T) {
	result := &config.AssemblyResult{
		Workflow: config.WorkflowProperties{
			Name: "CI",
		},
		Jobs:        []*config.AssembledJob{},
		SourceFiles: []string{"conf.yml"},
	}

	out := mustRender(t, result)

	// The output must still contain a jobs key.
	if !strings.Contains(out, "jobs:") {
		t.Errorf("expected 'jobs:' in output even with no jobs:\n%s", out)
	}
	// No stage comments should appear.
	if strings.Contains(out, "Stage:") {
		t.Errorf("expected no stage comments with empty jobs list:\n%s", out)
	}
}

// ---------------------------------------------------------------------------
// TestRender_DisplayNameRendered
// ---------------------------------------------------------------------------

func TestRender_DisplayNameRendered(t *testing.T) {
	jobs := []*config.AssembledJob{
		{
			ID:          "build--drupal--docker-php",
			Stage:       "build",
			DisplayName: "Build PHP - drupal [build]",
			Properties:  map[string]any{"runs-on": "ubuntu-latest"},
		},
	}

	out := mustRender(t, minimalResult(jobs))

	if !strings.Contains(out, "name: Build PHP - drupal [build]") {
		t.Errorf("expected display name in output:\n%s", out)
	}

	// Verify name appears right after the job ID line.
	lines := strings.Split(out, "\n")
	for i, line := range lines {
		if strings.Contains(line, "build--drupal--docker-php:") {
			if i+1 >= len(lines) {
				t.Fatal("job ID is on the last line, no name follows")
			}
			nextLine := strings.TrimSpace(lines[i+1])
			if !strings.HasPrefix(nextLine, "name:") {
				t.Errorf("expected 'name:' immediately after job ID, got: %q", nextLine)
			}
			break
		}
	}
}
