// Package render generates the final GitHub Actions workflow YAML output.
package render

import (
	"bytes"
	"fmt"
	"strings"

	"github.com/sparkfabrik/github-ci-assembler/internal/config"
	"gopkg.in/yaml.v3"
)

// Render generates the complete GitHub Actions workflow YAML from the assembly result.
func Render(result *config.AssemblyResult) ([]byte, error) {
	var buf bytes.Buffer

	// Write the auto-generated header.
	writeHeader(&buf, result.SourceFiles)

	// Build the root document node for controlled ordering.
	doc := &yaml.Node{
		Kind: yaml.DocumentNode,
	}
	root := &yaml.Node{
		Kind: yaml.MappingNode,
	}
	doc.Content = []*yaml.Node{root}

	// Add workflow-level properties in the canonical order.
	if result.Workflow.Name != "" {
		addScalarMapping(root, "name", result.Workflow.Name)
	}
	if result.Workflow.On != nil {
		if err := addAnyMapping(root, "on", result.Workflow.On); err != nil {
			return nil, fmt.Errorf("rendering 'on': %w", err)
		}
	}
	if result.Workflow.Defaults != nil {
		if err := addAnyMapping(root, "defaults", result.Workflow.Defaults); err != nil {
			return nil, fmt.Errorf("rendering 'defaults': %w", err)
		}
	}
	if result.Workflow.Env != nil {
		if err := addAnyMapping(root, "env", result.Workflow.Env); err != nil {
			return nil, fmt.Errorf("rendering 'env': %w", err)
		}
	}
	if result.Workflow.Permissions != nil {
		if err := addAnyMapping(root, "permissions", result.Workflow.Permissions); err != nil {
			return nil, fmt.Errorf("rendering 'permissions': %w", err)
		}
	}

	// Add jobs section.
	jobsNode, err := renderJobs(result.Jobs)
	if err != nil {
		return nil, fmt.Errorf("rendering jobs: %w", err)
	}
	addKeyNode(root, "jobs", jobsNode)

	// Marshal to YAML.
	yamlBytes, err := marshalNode(doc)
	if err != nil {
		return nil, fmt.Errorf("marshaling YAML: %w", err)
	}

	buf.Write(yamlBytes)
	return buf.Bytes(), nil
}

// writeHeader writes the auto-generated header comment.
func writeHeader(buf *bytes.Buffer, sourceFiles []config.SourceFile) {
	buf.WriteString("# AUTO-GENERATED by gh-ci-assembler — do not edit manually\n")
	buf.WriteString("# Contributing files:\n")
	for _, f := range sourceFiles {
		fmt.Fprintf(buf, "#   - %s: %s\n", f.Kind, f.Path)
	}
	buf.WriteString("\n")
}

// renderJobs builds the YAML node for the jobs section.
func renderJobs(jobs []*config.AssembledJob) (*yaml.Node, error) {
	jobsNode := &yaml.Node{
		Kind: yaml.MappingNode,
	}

	// Group jobs by stage in order, collecting disabled comments per stage.
	type stageGroup struct {
		stageName        string
		activeJobs       []*config.AssembledJob
		disabledComments []string
	}

	// Build ordered stage groups preserving the input order.
	var stageOrder []string
	stageMap := make(map[string]*stageGroup)
	for _, j := range jobs {
		if _, exists := stageMap[j.Stage]; !exists {
			stageOrder = append(stageOrder, j.Stage)
			stageMap[j.Stage] = &stageGroup{stageName: j.Stage}
		}
		sg := stageMap[j.Stage]
		if j.Disabled {
			sg.disabledComments = append(sg.disabledComments,
				fmt.Sprintf("%s: %s", j.ID, j.DisabledComment))
		} else {
			sg.activeJobs = append(sg.activeJobs, j)
		}
	}

	// Render each stage group.
	for _, stageName := range stageOrder {
		sg := stageMap[stageName]

		// Skip stages with no active jobs and no disabled comments.
		if len(sg.activeJobs) == 0 && len(sg.disabledComments) == 0 {
			continue
		}

		// Build the stage header comment.
		stageComment := fmt.Sprintf(" ── Stage: %s ", stageName)
		stageComment = stageComment + strings.Repeat("─", 58-len(stageComment))

		if len(sg.activeJobs) == 0 {
			// Stage only has disabled jobs — attach as foot comment on last value.
			var fullComment string
			for _, dc := range sg.disabledComments {
				fullComment += fmt.Sprintf("\n %s", dc)
			}
			commentText := stageComment + fullComment
			if len(jobsNode.Content) >= 2 {
				lastValue := jobsNode.Content[len(jobsNode.Content)-1]
				lastValue.FootComment = commentText
			}
			continue
		}

		// Render active jobs.
		for i, j := range sg.activeJobs {
			jobNode, err := renderSingleJob(j)
			if err != nil {
				return nil, fmt.Errorf("rendering job %q: %w", j.ID, err)
			}

			keyNode := &yaml.Node{
				Kind:  yaml.ScalarNode,
				Value: j.ID,
				Tag:   "!!str",
			}

			// Attach stage header to the first job in the stage.
			if i == 0 {
				headerComment := stageComment
				// Also prepend any disabled job comments for this stage.
				for _, dc := range sg.disabledComments {
					headerComment += fmt.Sprintf("\n %s", dc)
				}
				keyNode.HeadComment = headerComment
			}

			jobsNode.Content = append(jobsNode.Content, keyNode, jobNode)
		}
	}

	return jobsNode, nil
}

// renderSingleJob builds the YAML mapping node for a single job.
func renderSingleJob(j *config.AssembledJob) (*yaml.Node, error) {
	jobNode := &yaml.Node{
		Kind: yaml.MappingNode,
	}

	// Add display name first.
	addScalarMapping(jobNode, "name", j.DisplayName)

	// Add needs if present.
	if len(j.ComputedNeeds) > 0 {
		needsNode := &yaml.Node{
			Kind:  yaml.SequenceNode,
			Style: yaml.FlowStyle,
		}
		for _, n := range j.ComputedNeeds {
			needsNode.Content = append(needsNode.Content, &yaml.Node{
				Kind:  yaml.ScalarNode,
				Value: n,
				Tag:   "!!str",
			})
		}
		addKeyNode(jobNode, "needs", needsNode)
	}

	// Add remaining properties in a controlled order.
	// These are the common GHA job properties in a logical order.
	orderedKeys := []string{
		"runs-on", "permissions", "environment", "concurrency",
		"if", "timeout-minutes", "continue-on-error",
		"container", "services", "env", "defaults",
		"strategy", "outputs", "steps",
	}

	// First, add known keys in order.
	added := map[string]bool{"name": true, "needs": true}
	for _, key := range orderedKeys {
		if val, ok := j.Properties[key]; ok {
			if err := addAnyMapping(jobNode, key, val); err != nil {
				return nil, fmt.Errorf("key %q: %w", key, err)
			}
			added[key] = true
		}
	}

	// Then, add any remaining unknown keys alphabetically.
	var remainingKeys []string
	for key := range j.Properties {
		if !added[key] {
			remainingKeys = append(remainingKeys, key)
		}
	}
	sortStrings(remainingKeys)
	for _, key := range remainingKeys {
		if err := addAnyMapping(jobNode, key, j.Properties[key]); err != nil {
			return nil, fmt.Errorf("key %q: %w", key, err)
		}
	}

	return jobNode, nil
}

// addScalarMapping adds a string key-value pair to a mapping node.
func addScalarMapping(node *yaml.Node, key, value string) {
	node.Content = append(node.Content,
		&yaml.Node{Kind: yaml.ScalarNode, Value: key, Tag: "!!str"},
		&yaml.Node{Kind: yaml.ScalarNode, Value: value, Tag: "!!str"},
	)
}

// addKeyNode adds a key with an arbitrary value node to a mapping node.
func addKeyNode(node *yaml.Node, key string, valueNode *yaml.Node) {
	node.Content = append(node.Content,
		&yaml.Node{Kind: yaml.ScalarNode, Value: key, Tag: "!!str"},
		valueNode,
	)
}

// addAnyMapping marshals an arbitrary value and adds it to a mapping node.
func addAnyMapping(node *yaml.Node, key string, value any) error {
	valueNode := &yaml.Node{}
	if err := valueNode.Encode(value); err != nil {
		return fmt.Errorf("encoding value for key %q: %w", key, err)
	}
	node.Content = append(node.Content,
		&yaml.Node{Kind: yaml.ScalarNode, Value: key, Tag: "!!str"},
		valueNode,
	)
	return nil
}

// marshalNode marshals a yaml.Node to bytes with 2-space indentation.
func marshalNode(node *yaml.Node) ([]byte, error) {
	var buf bytes.Buffer
	enc := yaml.NewEncoder(&buf)
	enc.SetIndent(2)
	if err := enc.Encode(node); err != nil {
		return nil, err
	}
	if err := enc.Close(); err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}

// sortStrings sorts a string slice in place.
func sortStrings(s []string) {
	for i := 1; i < len(s); i++ {
		for j := i; j > 0 && s[j] < s[j-1]; j-- {
			s[j], s[j-1] = s[j-1], s[j]
		}
	}
}
